
<<<<<<< HEAD
<!-- FAZER UM COMPONENTE PARA O FORM PASSANDO UM PARAMETRO PARA ACTION-->
<!-- ESSE FORM SERÁ USADO NAS VISÕES DE CADASTRO E EDITAR USUÁRIO -->
=======
<!-- FAZER UM COMPONENTE PARA O FORM PASSANDO UM PARAMENTRO PARA ACTION-->
<!-- ESSE FORM SERÁ USADO NAS VISÃO DE CADASTRO E EDITAR USUÁRIO -->
>>>>>>> master
<div>
	<form method="post" action="{{ $action }}">
		@csrf
		<!-- CAMPOS -->
	</form>	
</div>
